# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  displayName: 'Ejecutar Maven con app/pom.xml'
  inputs:
    mavenPomFile: 'app/pom.xml'
    codeCoverageToolOption: 'Cobertura'
  
    
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'  # Nombre descriptivo con destino
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'         # Carpeta de origen
    Contents: '**/*.jar'                              # Archivos a copiar (todos los .jar)
    TargetFolder: '$(Build.ArtifactStagingDirectory)' # Carpeta de destino
    CleanTargetFolder: true                           # Limpia la carpeta destino antes de copiar
    preserveTimestamp: true                           # Preserva las marcas de tiempo de los archivos
    condition: succeededOrFailed() 
  
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts: drop'  # Nombre visible con el nombre del artefacto
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Ruta donde están los artefactos
    ArtifactName: 'drop'                               # Nombre del artefacto
    PublishLocation: 'Container'                       # Lugar donde se publican (contenedor)
    condition: succeededOrFailed() 
